[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router"] }
ui = { workspace = true }
wasm-bindgen = "0.2.100"

[features]
default = []
web = ["dioxus/web"]
server = ["dioxus/server"]
